# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZEFYEnr66eQRGgyqgaDlg7fFyE9IkVpM
"""

# api_mnist.py

import io
import torch
import torch.nn as nn
from fastapi import FastAPI, File, UploadFile
from PIL import Image
import torchvision.transforms as transforms
from fastapi.middleware.cors import CORSMiddleware
app = FastAPI(title="Savita API")

# Allow frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
# DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# -----------------------------
# 1. Define Model (same as training)
# -----------------------------
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()

        self.conv1 = nn.Conv2d(1, 32, kernel_size=3)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3)

        self.pool = nn.MaxPool2d(2)
        self.relu = nn.ReLU()

        self.fc1 = nn.Linear(64 * 5 * 5, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.relu(self.conv1(x))
        x = self.pool(x)

        x = self.relu(self.conv2(x))
        x = self.pool(x)

        x = x.view(-1, 64 * 5 * 5)

        x = self.relu(self.fc1(x))
        x = self.fc2(x)

        return x

# -----------------------------
# 2. Load Model
# -----------------------------
device = torch.device("cpu")

model = CNN()
model.load_state_dict(torch.load("cnn_mnist_weights.pth", map_location=device))
model.to(device)
model.eval()

# -----------------------------
# 3. FastAPI App
# -----------------------------
app = FastAPI(title="MNIST CNN API")

# -----------------------------
# 4. Image Preprocessing
# -----------------------------
transform = transforms.Compose([
    transforms.Grayscale(),
    transforms.Resize((28, 28)),
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

# -----------------------------
# 5. Routes
# -----------------------------
@app.get("/")
def home():
    return {"message": "MNIST CNN API is running"}

@app.post("/predict/")
async def predict(file: UploadFile = File(...)):

    # Read image
    contents = await file.read()
    image = Image.open(io.BytesIO(contents))

    # Preprocess
    image = transform(image).unsqueeze(0).to(device)

    # Prediction
    with torch.no_grad():
        outputs = model(image)
        _, predicted = torch.max(outputs, 1)

    return {
        "filename": file.filename,
        "predicted_digit": int(predicted.item())
    }
